# Generated by Django 2.0.8 on 2019-03-17 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('ug_college', models.CharField(max_length=70)),
                ('ug_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pg_college', models.CharField(blank=True, max_length=70)),
                ('pg_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('work_exp', models.DecimalField(decimal_places=0, max_digits=2)),
                ('resume', models.FileField(upload_to='resumes')),
                ('user', models.OneToOneField(on_delete='CASCASDE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
