# Generated by Django 2.0.8 on 2019-03-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(upload_to='users/resumes'),
        ),
    ]
