# Generated by Django 2.1.7 on 2019-03-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Qualification', models.CharField(max_length=1000)),
                ('Location', models.CharField(max_length=1000)),
                ('PAN', models.CharField(max_length=15)),
            ],
        ),
    ]
