# Generated by Django 2.1.7 on 2019-03-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(default='hello', max_length=100),
        ),
    ]
