# Generated by Django 2.1.7 on 2019-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190314_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password1',
            field=models.CharField(default='hello123', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password2',
            field=models.CharField(default='hello123', max_length=100),
        ),
    ]
